server:
  port: 8765

spring:
  application:
    name: todo-gateway
  config:
    import: configserver:http://localhost:8888
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: todo-main
#          uri: lb://todo-main
#          predicates:
#            - Path=/api/category/hi
#            - Method=GET

