server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          username: seoLeir
          password: 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
          basedir: file://D:/VCSprojects/todo/todo-cloud-config
          clone-on-start: true
          uri: https://github.com/seoLeir/todo-cloud-config.git
          default-label: main
          force-pull: true
  application:
    name: todo-config
